version: 2

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:bionic-curl-browsers-legacy
    working_directory: ~/cpplang
    steps:
      - checkout
        # Install related packages
      - run: sudo apt install cmake g++
        # Set up Google test
      - run: chmod +x setup_googletest.sh && ./setup_googletest.sh
        # Build project files
      - run: cmake . && make
        # Execute tests
      - run: ./cpplang_library
workflows:
  version: 2
  workflow:
    jobs:
      - build
